=== commandblock2/vscode-frosted-glass-theme/src-inject/config.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "properties": {
    "filter": {
      "type": "object",
      "order": 0,
      "description": "The filter used for frosted glassed effect. Check README for detailed description.",
      "patternProperties": {
        ".*": {
          "type": [
            "string",
            "object"
          ],
          "properties": {
            "filter": {
              "type": "string"
            },
            "disableBackgroundColor": {
              "type": "boolean"
            },
            "opacity": {
              "type": "number"
            }
          }
        }
      }
    },
    "transition": {
      "type": "string",
      "order": 1,
      "description": "CSS transition."
    },
    "svg": {
      "type": "array",
      "order": 2,
      "description": "The svgs that load on start. No tint (ie. no element current background info).",
      "items": {
        "type": "string"
      }
    },
    "tintSvg": {
      "type": "array",
      "order": 3,
      "markdownDescription": "The tint svgs that load on start. `--fgt-current-background` indicts current element background color.",
      "items": {
        "type": "string"
      }
    },
    "variable": {
      "type": "object",
      "order": 4,
      "description": "CSS variable. You may use them in settings and svgs.",
      "patternProperties": {
        ".*": {
          "type": "string"
        }
      }
    },
    "variableDark": {
      "type": "object",
      "order": 5,
      "description": "CSS variable in dark mode. You may use them in settings and svgs.",
      "patternProperties": {
        ".*": {
          "type": "string"
        }
      }
    },
    "additionalStyle": {
      "type": "array",
      "order": 6,
      "description": "Additional style paths. They will be appended to <head>. You can add custom animations or styles.",
      "items": {
        "type": "string"
      }
    },
    "opacity": {
      "type": "object",
      "properties": {
        "selection": {
          "type": "number",
          "description": "Menu selection opacity. This will blend into your theme color."
        },
        "border": {
          "type": "number",
          "description": "Border opacity. This will blend into your theme color."
        },
        "separator": {
          "type": "number",
          "description": "Menu separator opacity. This will blend into your theme color."
        },
        "minimap": {
          "type": "number",
          "description": "Minimap opacity."
        }
      }
    },
    "animation": {
      "type": "object",
      "description": "CSS animation. Key can also be css selector.",
      "patternProperties": {
        ".*": {
          "type": "string"
        }
      }
    },
    "effect": {
      "type": "object",
      "properties": {
        "revealEffect": {
          "type": "object",
          "description": "Reveal effect config.",
          "properties": {
            "lightColor": {
              "type": "string"
            },
            "gradientSize": {
              "type": [
                "number",
                "string"
              ],
              "description": "A number in px or a string type percentage ends with %."
            },
            "clickEffect": {
              "type": [
                "object",
                "null"
              ],
              "properties": {
                "size": {
                  "type": [
                    "number",
                    "string"
                  ],
                  "description": "A number in px or a string type percentage ends with %."
                },
                "speed": {
                  "type": "number"
                },
                "duration": {
                  "type": "number"
                }
              }
            }
          }
        },
        "flipEffect": {
          "type": "object",
          "description": "Flip effect config.",
          "properties": {
            "reducedDistanceFunc": {
              "type": "string",
              "description": "A function used to calculate reduced distance in px."
            },
            "transition": {
              "type": "string"
            },
            "perspective": {
              "type": "number",
              "description": "Perspective in cm."
            }
          }
        },
        "extendMenuFocusBackground": {
          "type": [
            "boolean",
            "string"
          ],
          "description": "Extend menu focus background. Set to false to use vanilla round corner style. Can also be set to color string as a new background color."
        },
        "disableForDisabledItem": {
          "type": "boolean",
          "description": "Disable effect for disabled menu item."
        }
      }
    },
    "borderRadius": {
      "type": "object",
      "description": "Border radius (with unit). Key can also be css selector.",
      "patternProperties": {
        ".*": {
          "type": "string"
        }
      }
    },
    "fakeMica": {
      "type": "object",
      "properties": {
        "enabled": {
          "type": "boolean",
          "description": "Enable fake mica.",
          "order": 0
        },
        "url": {
          "type": "string",
          "markdownDescription": "Url to wallpaper. Default to windows default wallpaper. For spotlight, you can use `C:/Users/<username>/AppData/Roaming/Microsoft/Windows/Themes/CachedFiles/<Something>.jpg`.",
          "order": 1
        },
        "filter": {
          "type": "string",
          "description": "The filter used for fake mica background.",
          "order": 2
        },
        "titlebarFix": {
          "type": [
            "number",
            "null"
          ],
          "description": "Fix titlebar opacity."
        },
        "editorBackgroundFix": {
          "type": "boolean",
          "markdownDescription": "Fix editor overlapping background. Leave `editor-container` as the final color."
        }
      }
    },
    "miscellaneous": {
      "type": "object",
      "properties": {
        "progressBarBehindSectionHeader": {
          "type": "boolean",
          "description": "Put progressBar behind sectionHeader so it glows behind header blur."
        },
        "disableFocusOutline": {
          "type": "boolean",
          "description": "Remove outline from focused elements."
        }
      }
    }
  }
}

=== commandblock2/vscode-frosted-glass-theme/src-inject/config.json
{
  "$schema": "./config.schema.json",
  "filter": {
    "default": {
      "filter": "saturate(var(--fgt-saturate)) url(#fgt-acrylic-{key})",
      "disableBackgroundColor": true,
      "opacity": 0.6
    },
    "minimap": "blur(30px)",
    "decorationsOverviewRuler": "blur(30px)",
    "terminalOverlay": "blur(30px)"
  },
  "transition": "300ms",
  "svg": [
    "../resource/mica.svg"
  ],
  "tintSvg": [
    "../resource/acrylic.svg"
  ],
  "variable": {
    "fgt-saturate": "120%",
    "fgt-luminosity-opacity": "45%",
    "fgt-mica-luminosity": "hsl(0, 0%, 80%)",
    "fgt-mica-brightness": "",
    "fgt-animation-curve": "300ms cubic-bezier(0, 0.8, 0.2, 1)",
    "fgt-revealEffect-lightColor": "#00000014"
  },
  "variableDark": {
    "fgt-luminosity-opacity": "85%",
    "fgt-mica-luminosity": "hsl(0, 0%, 20%)",
    "fgt-mica-brightness": "brightness(30%)",
    "fgt-revealEffect-lightColor": "#ffffff14"
  },
  "additionalStyle": [],
  "opacity": {
    "selection": 1,
    "border": 0.4,
    "separator": 0.7,
    "minimap": 0.4
  },
  "animation": {
    "menu": "var(--fgt-animation-curve) fgtDropdown",
    "dialog": "var(--fgt-animation-curve) fgtZoomIn",
    "dropdown": "var(--fgt-animation-curve) fgtDropdown",
    "hover": "var(--fgt-animation-curve) fgtDropdown",
    "notificationCenter": "var(--fgt-animation-curve) fgtFlyout, fgt-flipEffect",
    "notificationCenterHeader": "fgt-revealEffect",
    "notification": "",
    "menuItem": "fgt-revealEffect, fgt-flipEffect",
    "actionMenuItem": "",
    "button": "fgt-revealEffect, fgt-flipEffect",
    "iconActionLabel": "fgt-flipEffect",
    "tab": "fgt-revealEffect, fgt-flipEffect",
    "listItem": "fgt-revealEffect, fgt-flipEffect",
    "statusbarItem": "fgt-revealEffect, fgt-flipEffect",
    "activitybarItem": "fgt-revealEffect, fgt-flipEffect",
    "compositeBarItem": "fgt-revealEffect, fgt-flipEffect",
    "commandCenter": "fgt-revealEffect",
    "menubarTitle": "fgt-flipEffect",
    "settingsTreeItem": "",
    "paneHeader": "fgt-revealEffect, fgt-flipEffect"
  },
  "effect": {
    "revealEffect": {
      "lightColor": "var(--fgt-revealEffect-lightColor)",
      "gradientSize": "100%",
      "clickEffect": {
        "size": 40,
        "speed": 0.8,
        "duration": 300
      }
    },
    "flipEffect": {
      "reducedDistanceFunc": "radius < 50 ? 0.1 * radius : (radius < 200 ? 0.02 * radius : 4)",
      "transition": "30ms",
      "perspective": 60
    },
    "extendMenuFocusBackground": "var(--fgt-revealEffect-lightColor)",
    "disableForDisabledItem": false
  },
  "borderRadius": {
    "menu": "",
    "menuItem": "",
    "suggestWidget": "",
    "tab": "6px 6px 0 0"
  },
  "fakeMica": {
    "enabled": false,
    "url": "C:/Windows/Web/Wallpaper/Windows/img0.jpg",
    "filter": "saturate(var(--fgt-saturate)) url(#fgt-mica) var(--fgt-mica-brightness)",
    "position": "center center / auto no-repeat",
    "titlebarFix": 0.8,
    "editorBackgroundFix": true
  },
  "miscellaneous": {
    "progressBarBehindSectionHeader": false,
    "disableFocusOutline": false
  }
}
